PREFIX sense:  <http://w3id.org/explainability/sense#>
PREFIX s: <http://w3id.org/explainability/sense#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
 
    SELECT distinct ?causesensor ?cause ?cset ?ceet ?relation ?effectsensor ?effect ?set ?eet
    WHERE {{
    ?cause ?relation ?effect .
        ?effect (s:causallyRelated)* s:DemandEnvelopeViolation_State_f519707a-b5e7-44ce-bc3e-37b68b8b4565 .
    ?relation rdfs:subPropertyOf s:causallyRelated .
    ?causeobservation sosa:hasResult ?cause .
    ?causesensor sosa:madeObservation ?causeobservation .
    ?effectobservation sosa:hasResult ?effect .
    ?effectsensor sosa:madeObservation ?effectobservation .
    ?effect s:hasStartEvent ?se .
    ?effect s:hasEndEvent ?ee .
    ?seo sosa:hasResult ?se .
    ?seo sosa:phenomenonTime ?set .
    ?eeo sosa:hasResult ?ee .
    ?eeo sosa:phenomenonTime ?eet .
    ?cause s:hasStartEvent ?cse .
    ?cause s:hasEndEvent ?cee .
    ?cseo sosa:hasResult ?cse .
    ?cseo sosa:phenomenonTime ?cset .
    ?ceeo sosa:hasResult ?cee .
    ?ceeo sosa:phenomenonTime ?ceet .
    FILTER(?relation != s:causallyRelated) .
    }}