PREFIX s: <http://w3id.org/explainability/sense#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX : <http://example.org/seehub#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select *
where { 
    ?p a sosa:Sensor .
    ?p sosa:observes ?property
} 
