PREFIX s: <http://w3id.org/explainability/sense#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX : <http://example.org/seehub#>
select *
where { 
	?p a sosa:Platform .
    ?accessRight s:allowsAccessTo ?p .
    ?userRole a s:UserRole .
    ?userRole :containsAccessRights ?accessRight .
    
}