PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX sense: <http://w3id.org/explainability/sense#>
PREFIX : <http://example.org/seehub#>
select *
where { 
    ?statetype a sense:StateType .
    ?causality sense:effect ?statetype ;
        sense:cause ?cause .
}